// WHIT-703 slice 1 — the cycle export becomes an Excel file (.xlsx) with two tabs.
// The generated bytes are unzipped with fflate (the library the writer is built on) and
// each sheet's XML is read back into a grid of cells. Expected values are written by hand
// from the card's column spec (same rules as WHIT-700's CSV).
import { describe, it, expect, jest, beforeEach } from '@jest/globals';

jest.mock('../auth', () => require('./support/authMock').authTokenSpyModule('test-token'));

const fileInstances: { args: unknown[]; created: unknown[]; written: unknown[]; uri: string }[] = [];
jest.mock('expo-file-system', () => ({
  Paths: { cache: { uri: 'file:///cache/' } },
  File: class {
    args: unknown[];
    created: unknown[] = [];
    written: unknown[] = [];
    uri = 'file:///cache/out.xlsx';
    constructor(...args: unknown[]) {
      this.args = args;
      fileInstances.push(this);
    }
    create(options: unknown) { this.created.push(options); }
    write(content: unknown) { this.written.push(content); }
  },
}));
jest.mock('expo-sharing', () => ({ shareAsync: jest.fn(async () => undefined) }));

import { unzipSync, strFromU8 } from 'fflate';
import * as Sharing from 'expo-sharing';
import { Paths } from 'expo-file-system';
import { buildCycleWorkbook } from '../cycleExport';
import { shareCycleExport } from '../cycleShare';
import type { CycleTransaction } from '../api';
import { cat, txn } from './factory';
import type { Category } from '../types';

const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const XLSX_UTI = 'org.openxmlformats.spreadsheetml.sheet';
const TRANSACTION_HEADER = [
  'Date', 'Amount', 'Parent category', 'Category', 'Description', 'Account', 'Status', 'Counts to budget',
];
const BUDGET_HEADER = [
  'Parent category', 'Category', 'Budget', 'Spent', 'Pending', 'Left to spend', 'Carry-over', 'Available',
];

const shareAsync = Sharing.shareAsync as jest.MockedFunction<typeof Sharing.shareAsync>;

// ---- a tiny xlsx reader for the tests -------------------------------------------------

type ReadCell = { value: string | number; numeric: boolean; twoDecimals: boolean };
type Workbook = { names: string[]; sheets: Record<string, (ReadCell | null)[][]> };

function unescapeXml(text: string): string {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)))
    .replace(/&amp;/g, '&');
}

function attr(tag: string, name: string): string | undefined {
  const match = tag.match(new RegExp(`(?:^|\\s)${name}="([^"]*)"`));
  return match ? unescapeXml(match[1]) : undefined;
}

function columnIndex(letters: string): number {
  let index = 0;
  for (const letter of letters) index = index * 26 + (letter.charCodeAt(0) - 64);
  return index - 1;
}

function textOf(xml: string): string {
  return [...xml.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map((m) => unescapeXml(m[1])).join('');
}

function readWorkbook(bytes: Uint8Array): Workbook {
  const files = unzipSync(bytes);
  const read = (path: string) => strFromU8(files[path]);

  const workbookXml = read('xl/workbook.xml');
  const relsXml = read('xl/_rels/workbook.xml.rels');
  const targets: Record<string, string> = {};
  for (const [tag] of relsXml.matchAll(/<Relationship\s[^>]*>/g)) {
    targets[attr(tag, 'Id')!] = attr(tag, 'Target')!;
  }

  const sharedStrings: string[] = files['xl/sharedStrings.xml']
    ? [...read('xl/sharedStrings.xml').matchAll(/<si>([\s\S]*?)<\/si>/g)].map((m) => textOf(m[1]))
    : [];

  const numFmtCodes: Record<string, string> = {};
  const xfFormats: string[] = [];
  if (files['xl/styles.xml']) {
    const styles = read('xl/styles.xml');
    for (const [tag] of styles.matchAll(/<numFmt\s[^>]*>/g)) {
      numFmtCodes[attr(tag, 'numFmtId')!] = attr(tag, 'formatCode')!;
    }
    const cellXfs = styles.match(/<cellXfs[^>]*>([\s\S]*?)<\/cellXfs>/);
    if (cellXfs) {
      for (const [tag] of cellXfs[1].matchAll(/<xf\s[^>]*>/g)) xfFormats.push(attr(tag, 'numFmtId') ?? '0');
    }
  }
  const isTwoDecimals = (style: string | undefined) => {
    const numFmtId = xfFormats[Number(style ?? 0)];
    return numFmtId === '2' || numFmtCodes[numFmtId ?? ''] === '0.00';
  };

  const names: string[] = [];
  const sheets: Workbook['sheets'] = {};
  for (const [tag] of workbookXml.matchAll(/<sheet\s[^>]*>/g)) {
    const name = attr(tag, 'name')!;
    const relId = attr(tag, 'r:id')!;
    const target = targets[relId].replace(/^\/?(xl\/)?/, '');
    const sheetXml = read(`xl/${target}`);
    const grid: (ReadCell | null)[][] = [];
    for (const rowMatch of sheetXml.matchAll(/<row\b[^>]*?(?:\/>|>([\s\S]*?)<\/row>)/g)) {
      const rowNumber = Number(attr(rowMatch[0].match(/<row\b[^>]*>/)![0], 'r') ?? grid.length + 1);
      const cells: (ReadCell | null)[] = [];
      for (const cellMatch of (rowMatch[1] ?? '').matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)) {
        const cellTag = `<c ${cellMatch[1]}>`;
        const inner = cellMatch[2] ?? '';
        const ref = attr(cellTag, 'r')!;
        const column = columnIndex(ref.replace(/\d+/g, ''));
        const type = attr(cellTag, 't');
        const v = inner.match(/<v>([\s\S]*?)<\/v>/);
        let cell: ReadCell | null = null;
        if (type === 'inlineStr') cell = { value: textOf(inner), numeric: false, twoDecimals: false };
        else if (type === 's' && v) cell = { value: sharedStrings[Number(v[1])], numeric: false, twoDecimals: false };
        else if (type === 'str' && v) cell = { value: unescapeXml(v[1]), numeric: false, twoDecimals: false };
        else if (v) cell = { value: Number(v[1]), numeric: true, twoDecimals: isTwoDecimals(attr(cellTag, 's')) };
        while (cells.length < column) cells.push(null);
        cells[column] = cell;
      }
      while (cells.length && cells[cells.length - 1] === null) cells.pop();
      while (grid.length < rowNumber - 1) grid.push([]);
      grid[rowNumber - 1] = cells;
    }
    names.push(name);
    sheets[name] = grid;
  }
  return { names, sheets };
}

function values(grid: (ReadCell | null)[][]): (string | number | null)[][] {
  return grid.map((row) => row.map((cell) => (cell ? cell.value : null)));
}

// ---- fixtures -------------------------------------------------------------------------

const CATS: Category[] = [
  cat({ id: 'food', name: 'Food', parent: null }),
  cat({ id: 'eating-out', name: 'Eating out', parent: 'food' }),
  cat({ parent: 'eating-out' }),   // 3 levels deep
  cat({ id: 'groceries', name: 'Groceries', parent: null }),
  cat({ id: 'orphan', name: 'Orphan', parent: 'gone' }),                 // parent the app doesn't know
];
const category = (id: string) => CATS.find((c) => c.id === id);

function row(over: Partial<CycleTransaction>): CycleTransaction {
  return { ...txn(), counts_to_budget_effective: true, ...over };
}

const TRANSACTIONS: CycleTransaction[] = [
  row({ transaction_id: 'a', date: '2026-07-25', amount: -12.5, category: 'coffee',
    merchant_name: 'Bean & "The" <Cafe>', account_name: 'Everyday', status: 'pending' }),
  row({ transaction_id: 'b', date: '2026-07-20', amount: 1000, category: 'groceries',
    merchant_name: '', description: 'PAY\nROLL', account_name: 'Savings', status: 'posted',
    counts_to_budget_effective: false }),
  row({ transaction_id: 'c', date: '2026-07-10', amount: -3, category: null,
    merchant_name: 'Kiosk', account_name: 'Everyday', status: 'posted' }),
  row({ transaction_id: 'd', date: '2026-07-05', amount: -7.1, category: 'not-a-category',
    merchant_name: 'Mystery', account_name: 'Everyday', status: 'posted', counts_to_budget_effective: false }),
  row({ transaction_id: 'e', date: '2026-07-02', amount: -20, category: 'orphan',
    merchant_name: 'Shop', account_name: 'Everyday', status: 'posted' }),
  row({ transaction_id: 'f', date: '2026-07-01', amount: -4.25, category: 'eating-out',
    merchant_name: 'Diner', account_name: 'Everyday', status: 'posted' }),
];

const EXPECTED_TRANSACTION_ROWS = [
  TRANSACTION_HEADER,
  ['2026-07-25', -12.5, 'Food', 'Cafes & Coffee', 'Bean & "The" <Cafe>', 'Everyday', 'pending', 'Yes'],
  ['2026-07-20', 1000, 'Groceries', 'Groceries', 'PAY\nROLL', 'Savings', 'posted', 'No'],
  ['2026-07-10', -3, 'Uncategorised', 'Uncategorised', 'Kiosk', 'Everyday', 'posted', 'Yes'],
  ['2026-07-05', -7.1, 'Uncategorised', 'Uncategorised', 'Mystery', 'Everyday', 'posted', 'No'],
  ['2026-07-02', -20, 'Orphan', 'Orphan', 'Shop', 'Everyday', 'posted', 'Yes'],
  ['2026-07-01', -4.25, 'Food', 'Eating out', 'Diner', 'Everyday', 'posted', 'Yes'],
];

beforeEach(() => {
  fileInstances.length = 0;
  shareAsync.mockReset();
  shareAsync.mockResolvedValue(undefined);
});

describe('buildCycleWorkbook', () => {
  it('user can export a cycle as an Excel workbook with a Transactions tab of numeric amounts and a Budgets tab', () => {
    const bytes = buildCycleWorkbook(
      { start: '2026-07-01', end: '2026-07-31', transactions: TRANSACTIONS },
      category,
      false,
    );

    expect(Object.prototype.toString.call(bytes)).toBe('[object Uint8Array]');
    const workbook = readWorkbook(bytes);

    expect(workbook.names).toEqual(['Transactions', 'Budgets']);

    const transactions = workbook.sheets.Transactions;
    expect(values(transactions)).toEqual(EXPECTED_TRANSACTION_ROWS);
    for (const dataRow of transactions.slice(1)) {
      expect(dataRow[1]).toMatchObject({ numeric: true, twoDecimals: true });
      for (const index of [0, 2, 3, 4, 5, 6, 7]) expect(dataRow[index]?.numeric).toBe(false);
    }

    // No `budgets` in the reply (an old server, or slice 1) → the Budgets tab is its titles only.
    expect(values(workbook.sheets.Budgets)).toEqual([BUDGET_HEADER]);
  });
});

describe('shareCycleExport', () => {
  it('user can share last cycle as an .xlsx file with the Excel file type', async () => {
    const fetchMock = jest.fn(async () => ({
      ok: true,
      status: 200,
      json: async () => ({ start: '2026-06-01', end: '2026-06-30', transactions: TRANSACTIONS }),
    }));
    (globalThis as unknown as { fetch: unknown }).fetch = fetchMock;

    await shareCycleExport(1, category);

    expect((fetchMock.mock.calls[0] as unknown as [string])[0]).toMatch(/\/transactions\/cycle\?cycle=1$/);
    expect(fileInstances).toHaveLength(1);
    const [file] = fileInstances;
    expect(file.args).toEqual([Paths.cache, 'transactions_2026-06-01_to_2026-06-30.xlsx']);
    expect(file.created).toEqual([{ overwrite: true }]);
    expect(file.written).toHaveLength(1);
    const written = file.written[0] as Uint8Array;
    expect(Object.prototype.toString.call(written)).toBe('[object Uint8Array]');

    const workbook = readWorkbook(written);
    expect(workbook.names).toEqual(['Transactions', 'Budgets']);
    expect(values(workbook.sheets.Transactions)).toEqual(EXPECTED_TRANSACTION_ROWS);

    expect(shareAsync).toHaveBeenCalledTimes(1);
    const [uri, options] = shareAsync.mock.calls[0];
    expect(uri).toBe(file.uri);
    expect(options).toMatchObject({ mimeType: XLSX_MIME, UTI: XLSX_UTI });
  });
});
